// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrOboisE3bcKQFdtcLXAXbK-UdTFwLI_o',
    appId: '1:278136132490:web:a88532c443f237b005ee73',
    messagingSenderId: '278136132490',
    projectId: 'electricity-assistant-fb2f7',
    authDomain: 'electricity-assistant-fb2f7.firebaseapp.com',
    storageBucket: 'electricity-assistant-fb2f7.appspot.com',
    measurementId: 'G-6N4TEWVZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZhbBpEKdDbJr4dfTyApeDbQACBk4pJJs',
    appId: '1:278136132490:android:813fc535017fc49405ee73',
    messagingSenderId: '278136132490',
    projectId: 'electricity-assistant-fb2f7',
    storageBucket: 'electricity-assistant-fb2f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0lbr3vbMGdZVDuC_pc-6yvSVT7Hu1Mk',
    appId: '1:278136132490:ios:4c75d5541dbbe1a205ee73',
    messagingSenderId: '278136132490',
    projectId: 'electricity-assistant-fb2f7',
    storageBucket: 'electricity-assistant-fb2f7.appspot.com',
    iosBundleId: 'com.example.electricityAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0lbr3vbMGdZVDuC_pc-6yvSVT7Hu1Mk',
    appId: '1:278136132490:ios:4c75d5541dbbe1a205ee73',
    messagingSenderId: '278136132490',
    projectId: 'electricity-assistant-fb2f7',
    storageBucket: 'electricity-assistant-fb2f7.appspot.com',
    iosBundleId: 'com.example.electricityAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrOboisE3bcKQFdtcLXAXbK-UdTFwLI_o',
    appId: '1:278136132490:web:ce127267dc15a95b05ee73',
    messagingSenderId: '278136132490',
    projectId: 'electricity-assistant-fb2f7',
    authDomain: 'electricity-assistant-fb2f7.firebaseapp.com',
    storageBucket: 'electricity-assistant-fb2f7.appspot.com',
    measurementId: 'G-5TNY2ZG4G9',
  );
}
